# Generated by Django 3.0.2 on 2020-01-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('alias', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.IntegerField(unique=True)),
                ('alias', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('experiment_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_google_optimize.ExperimentVariant')),
            ],
        ),
    ]
