# Generated by Django 3.0.2 on 2020-01-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentvariant',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
