# Generated by Django 3.0.2 on 2020-01-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleexperiment',
            name='experiment_variant',
        ),
        migrations.AlterField(
            model_name='googleexperiment',
            name='experiment_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
