# Generated by Django 3.0.2 on 2020-01-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0002_auto_20200128_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleexperiment',
            name='experiment_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_google_optimize.ExperimentVariant'),
        ),
        migrations.AlterField(
            model_name='googleexperiment',
            name='experiment_id',
            field=models.CharField(max_length=50),
        ),
    ]
