# Generated by Django 3.0.2 on 2020-01-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0002_experimentcookie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentcookie',
            options={'verbose_name': 'Experiment Cookie(Debug mode)'},
        ),
        migrations.AlterField(
            model_name='experimentcookie',
            name='active_variant_index',
            field=models.IntegerField(help_text='Overrides the cookie and sets the active variant for this experiment'),
        ),
    ]
