# Generated by Django 3.0.2 on 2020-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0003_auto_20200129_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentcookie',
            options={},
        ),
        migrations.AlterField(
            model_name='experimentcookie',
            name='active_variant_index',
            field=models.IntegerField(help_text='Overrides the cookie and sets the active variant for this experiment\nNOTE: ONLY WORKS IN DEBUG MODE'),
        ),
    ]
