# Generated by Django 3.0.2 on 2020-01-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0003_auto_20200128_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleexperiment',
            name='experiment_variant',
        ),
        migrations.AddField(
            model_name='googleexperiment',
            name='experiment_variant',
            field=models.ManyToManyField(to='django_google_optimize.ExperimentVariant'),
        ),
    ]
