# Generated by Django 3.0.2 on 2020-01-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0005_auto_20200128_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleexperiment',
            name='experiment_variant',
        ),
        migrations.AddField(
            model_name='experimentvariant',
            name='experiment_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_google_optimize.GoogleExperiment'),
        ),
    ]
