# Generated by Django 3.0.2 on 2020-01-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0006_auto_20200128_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleexperiment',
            name='alias',
        ),
        migrations.AddField(
            model_name='googleexperiment',
            name='experiment_alias',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='experimentvariant',
            name='alias',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='googleexperiment',
            name='experiment_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
