# Generated by Django 3.0.2 on 2020-01-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0007_auto_20200128_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentvariant',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='experimentvariant',
            unique_together={('index', 'experiment_variant')},
        ),
    ]
