# Generated by Django 3.0.2 on 2020-01-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0008_auto_20200128_0744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experimentvariant',
            unique_together={('index', 'alias', 'experiment_variant')},
        ),
    ]
