# Generated by Django 3.0.2 on 2020-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0009_auto_20200128_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentvariant',
            name='alias',
            field=models.CharField(max_length=50),
        ),
    ]
