# Generated by Django 3.0.2 on 2020-01-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_google_optimize', '0010_auto_20200128_0746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experimentvariant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='experimentvariant',
            constraint=models.UniqueConstraint(fields=('alias', 'experiment_variant'), name='Can not have the same alias within an experiment_variant'),
        ),
        migrations.AddConstraint(
            model_name='experimentvariant',
            constraint=models.UniqueConstraint(fields=('index', 'experiment_variant'), name='Can not have the same index within an experiment_variant'),
        ),
    ]
