---
name: Test
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    tags:
      - .*

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8.0
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: tox -e docs
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8.0
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: tox -e release
