---
name: Lint
on: [push]  # yamllint disable-line rule:truthy
env:
  PYTHON_VERSION: "3.8"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python $PYTHON_VERSION
        uses: actions/setup-python@v1
        with:
          python-version: $PYTHON_VERSION
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -e isort,black
